// <auto-generated />
using CoreMVCAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreMVCAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreMVCAPI.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe",
                            Position = "Manager",
                            Salary = 50000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith",
                            Position = "Developer",
                            Salary = 40000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Michael Brown",
                            Position = "Designer",
                            Salary = 45000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Emily Davis",
                            Position = "Tester",
                            Salary = 35000m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chris Johnson",
                            Position = "HR",
                            Salary = 38000m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sarah Wilson",
                            Position = "Accountant",
                            Salary = 42000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
